### ISSUE TITLE
Pragma parse error results in ugly backtrace

### ISSUE THREAD

**Issue by richq** [richq/cmake-lint#11]
From Dirk's comment on PR #6 

I just ran into this "feature". My CMake file had a comment line which looks like this:

    # lint_cmake: the next line does not follow the style guide to check that the linter detects this

While such a comment is very uncommon it might be better to only warn about it (if the pragma can't be parsed) but continue processing the file. My simple work around for now will be to slightly modify the comment to look like a pragma.

--

The result of this is pretty hideous:
```
Exception occurred while processing 'test.cmake:3':
Traceback (most recent call last):
  File "./bin/cmakelint", line 8, in <module>
    sys.exit(cmakelint.main.main())
  File "/usr/lib/python3.4/site-packages/cmakelint/main.py", line 502, in main
    ProcessFile(filename)
  File "/usr/lib/python3.4/site-packages/cmakelint/main.py", line 387, in ProcessFile
    return _ProcessFile(filename)
  File "/usr/lib/python3.4/site-packages/cmakelint/main.py", line 416, in _ProcessFile
    CheckLintPragma(filename, len(lines), l)
  File "/usr/lib/python3.4/site-packages/cmakelint/main.py", line 396, in CheckLintPragma
    _lint_state.SetFilters(line[len(linter_pragma_start):])
  File "/usr/lib/python3.4/site-packages/cmakelint/main.py", line 114, in SetFilters
    raise ValueError('Filter should start with - or +')
ValueError: Filter should start with - or +
```

**Comment by richq** [comment]
fixed in 47505cd2a00cdaf5b251dc05692ae557b12af93f
